/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iu;

import controladores.ControlVistaTablaPrecios;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import logica.Parking;
import logica.TipoVehiculo;

/**
 *
 * @author facun
 */
public class DialogoPrecios extends javax.swing.JFrame implements VistaTablaPrecios {
 String nombreParking;
 private final ControlVistaTablaPrecios controlador;
    /**
     * Creates new form DialogoPrecios
     * @param nombreparking
     */
    public DialogoPrecios(String nombreparking) {
        
        initComponents();
        this.nombreParking=nombreparking;
      this.controlador= new ControlVistaTablaPrecios(this);
       
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstParking = new javax.swing.JList<>();
        txtNuevoValor = new javax.swing.JTextField(10);
        lblTitulo = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nuevo valor:");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lstParking.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstParking);

        txtNuevoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoValorActionPerformed(evt);
            }
        });

        lblTitulo.setText("label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNuevoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNuevoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String valor= txtNuevoValor.getText();
       try {
    double nuevoValor = Double.parseDouble(valor);
  
        if (nuevoValor <= 0) {
            JOptionPane.showMessageDialog(null, "Valor inválido. El precio debe ser igual o mayor a cero.", "Error", JOptionPane.ERROR_MESSAGE);
       
        }
   String nombre= lstParking.getSelectedValue();
    double promedioTarifa = controlador.obtenerPromedioTarifa(nombre);
        
        if (nuevoValor >= 2 * promedioTarifa) {
            JOptionPane.showMessageDialog(null, "Valor demasiado alto. El sistema no permite dispersión de precios por encima del 100%. Ingrese un valor menor a " + (2 * promedioTarifa) + ".", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
   controlador.ObtenerTarifa(nombre, nuevoValor);
  
} catch (NumberFormatException e) {
    // Maneja la excepción si el texto no puede ser parseado a un entero
    JOptionPane.showMessageDialog(null, "El valor ingresado no es un número válido", "Error", JOptionPane.ERROR_MESSAGE);
}
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNuevoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoValorActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label lblTitulo;
    private javax.swing.JList<String> lstParking;
    private javax.swing.JTextField txtNuevoValor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarTabla(Parking p) {
    lblTitulo.setText(nombreParking);
       ArrayList<String> listaTarifas = new ArrayList<>();
        for (Map.Entry<TipoVehiculo, Double> entry : p.getTarifaHashmap().entrySet()) {
            listaTarifas.add(entry.getKey() + " " + entry.getValue());
        }
         
        String[] arrayTarifas = new String[listaTarifas.size()];
        arrayTarifas = listaTarifas.toArray(arrayTarifas);
        lstParking.setListData(arrayTarifas);
      
        
    }
    

    @Override
    public String GetNombre() {
  return nombreParking;    }
}
